// <auto-generated />
using System;
using EnergyMonitor.Client.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyMonitor.Migrations
{
    [DbContext(typeof(MeasurementsDbContext))]
    partial class MeasurementsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("EnergyMonitor.Client.Models.MqttDataItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Measurements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a10e9acf-f87d-4505-9d92-592590637a02"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 10, 818, DateTimeKind.Local).AddTicks(9620),
                            Topic = "solar_assistant/inverter_1/pv_power/state",
                            Value = "1400"
                        },
                        new
                        {
                            Id = new Guid("1cc59aa7-8b7d-4b5f-ad19-01d9f4536fd4"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 10, 818, DateTimeKind.Local).AddTicks(9679),
                            Topic = "solar_assistant/inverter_1/grid_power/state",
                            Value = "0"
                        },
                        new
                        {
                            Id = new Guid("dceb6be7-8eec-4556-8273-d66651221676"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 10, 818, DateTimeKind.Local).AddTicks(9681),
                            Topic = "solar_assistant/inverter_1/load_power/state",
                            Value = "875"
                        },
                        new
                        {
                            Id = new Guid("c5d93440-e38a-416a-8d8a-491792f7060b"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 10, 818, DateTimeKind.Local).AddTicks(9692),
                            Topic = "solar_assistant/total/battery_power/state",
                            Value = "525"
                        },
                        new
                        {
                            Id = new Guid("0561e634-bb84-4996-a75b-d85f4a81ecf3"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 10, 818, DateTimeKind.Local).AddTicks(9695),
                            Topic = "solar_assistant/total/battery_state_of_charge/state",
                            Value = "100"
                        },
                        new
                        {
                            Id = new Guid("56220a35-c088-4279-9bf4-01756e388b86"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 10, 818, DateTimeKind.Local).AddTicks(9697),
                            Topic = "solar_assistant/inverter_1/charger_source_priority/state",
                            Value = "Solar/Battery/Grid"
                        },
                        new
                        {
                            Id = new Guid("8432065c-1260-4cc4-962f-960ff118f7d8"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 10, 818, DateTimeKind.Local).AddTicks(9699),
                            Topic = "solar_assistant/inverter_1/device_mode/state",
                            Value = "Solar"
                        },
                        new
                        {
                            Id = new Guid("864b3b72-c932-4373-a98e-e75a2d78126b"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 9, 818, DateTimeKind.Local).AddTicks(9701),
                            Topic = "solar_assistant/inverter_1/pv_power/state",
                            Value = "1600"
                        },
                        new
                        {
                            Id = new Guid("850c520b-dd7d-43ba-857b-39f5b1b0ffed"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 9, 818, DateTimeKind.Local).AddTicks(9703),
                            Topic = "solar_assistant/inverter_1/grid_power/state",
                            Value = "0"
                        },
                        new
                        {
                            Id = new Guid("b2de39de-0427-441c-ba61-59b6b3f28643"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 9, 818, DateTimeKind.Local).AddTicks(9705),
                            Topic = "solar_assistant/inverter_1/load_power/state",
                            Value = "875"
                        },
                        new
                        {
                            Id = new Guid("9f8502cc-821b-4c41-818d-aefb88c7dfb6"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 9, 818, DateTimeKind.Local).AddTicks(9707),
                            Topic = "solar_assistant/total/battery_power/state",
                            Value = "725"
                        },
                        new
                        {
                            Id = new Guid("7ce2ac67-93a2-4907-a852-0b75b1eda4f4"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 9, 818, DateTimeKind.Local).AddTicks(9711),
                            Topic = "solar_assistant/total/battery_state_of_charge/state",
                            Value = "100"
                        },
                        new
                        {
                            Id = new Guid("4d07ac99-da08-4be8-8a77-1cdc73fdb9c4"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 9, 818, DateTimeKind.Local).AddTicks(9713),
                            Topic = "solar_assistant/inverter_1/charger_source_priority/state",
                            Value = "Solar/Battery/Grid"
                        },
                        new
                        {
                            Id = new Guid("5005d2a8-9801-4aa4-aa13-fb678675dcd1"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 9, 818, DateTimeKind.Local).AddTicks(9715),
                            Topic = "solar_assistant/inverter_1/device_mode/state",
                            Value = "Solar"
                        },
                        new
                        {
                            Id = new Guid("ff5573b6-6210-449f-ae26-7712cfc9efed"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 8, 818, DateTimeKind.Local).AddTicks(9717),
                            Topic = "solar_assistant/inverter_1/pv_power/state",
                            Value = "1700"
                        },
                        new
                        {
                            Id = new Guid("416b65e1-b321-4daf-b02f-bac093e5d5bc"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 8, 818, DateTimeKind.Local).AddTicks(9719),
                            Topic = "solar_assistant/inverter_1/grid_power/state",
                            Value = "0"
                        },
                        new
                        {
                            Id = new Guid("e1556e44-3722-4532-82f5-84264af2651b"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 8, 818, DateTimeKind.Local).AddTicks(9721),
                            Topic = "solar_assistant/inverter_1/load_power/state",
                            Value = "1050"
                        },
                        new
                        {
                            Id = new Guid("3b26e7ed-e769-4633-a025-cb2d8e85abfa"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 8, 818, DateTimeKind.Local).AddTicks(9722),
                            Topic = "solar_assistant/total/battery_power/state",
                            Value = "650"
                        },
                        new
                        {
                            Id = new Guid("697acfc1-20c5-4516-b635-23e91d84f961"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 8, 818, DateTimeKind.Local).AddTicks(9724),
                            Topic = "solar_assistant/total/battery_state_of_charge/state",
                            Value = "100"
                        },
                        new
                        {
                            Id = new Guid("3e53deac-0a81-4e4d-9084-d744bc94ba96"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 8, 818, DateTimeKind.Local).AddTicks(9728),
                            Topic = "solar_assistant/inverter_1/charger_source_priority/state",
                            Value = "Solar/Battery/Grid"
                        },
                        new
                        {
                            Id = new Guid("461b327f-a341-4663-b147-d113debbce42"),
                            Timestamp = new DateTime(2024, 4, 2, 17, 20, 8, 818, DateTimeKind.Local).AddTicks(9757),
                            Topic = "solar_assistant/inverter_1/device_mode/state",
                            Value = "Solar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
